### ISSUE TITLE
이미지 

### ISSUE THREAD

**Issue by 79fa** [youngjungju/SeyeongJuyoung#6]
screenshot 폴더 만들고 거기 이미지 업로드 하는 것 남았는데 
이미지를 어떻게 업로드 하는지 알아?

**Comment by youngjungju** [comment]
어어 그거 issue에 사진 끌어다가 놓으면 사진이 텍스트처럼 나오는데 그거 업로드 되면 할 수 있어 내가 폴더에 추가해 놓을께!!
